name: Prepare environment to run Nx targets
description: Runs all required steps to prepare runner to run a Nx target

permissions: write-all # required for AWS credentials

inputs:
  aws_account_id_development:
    description: AWS Account ID for development environment
    required: true
  nx_key:
    description: Nx Powerpack NX key
    required: true

runs:
  using: composite
  steps:
    - name: Configure AWS Credentials
      env:
        AWS_REGION: us-east-1
      uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
      with:
        role-to-assume: arn:aws:iam::${{ inputs.aws_account_id_development }}:role/GitHubActions-methodology-rules
        aws-region: ${{ env.AWS_REGION }}

    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@76907e7e5d3cd17ddb5e2b123389f054bffcdd03 # v4.0.4

    - uses: ./.github/actions/install-node-dependencies
