name: Install node dependencies
description: Install node dependencies with cache

permissions: write-all # required for AWS credentials

runs:
  using: composite

  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Set Node version
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        node-version-file: .nvmrc
        cache: pnpm

    - name: Install node dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
