export const rulesConfig = {
  'credit-order': ['rewards-distribution'],
  'mass-id': [
    'waste-mass-is-unique',
    'no-conflicting-recycled-id-or-credit',
    'project-period-limit',
    'participant-accreditations-and-verifications-requirements',
    'mass-id-qualifications',
    'regional-waste-classification',
    'geolocation-and-address-precision',
    'waste-origin-identification',
    'hauler-identification',
    'vehicle-identification',
    'driver-identification',
    'transport-manifest-data',
    'processor-identification',
    'recycler-identification',
    'weighing',
    'drop-off-at-recycler',
    'mass-id-sorting',
    'composting-cycle-timeframe',
    'recycling-manifest-data',
  ],
  'recycled-id': ['rewards-distribution'],
} as const;
