name: Deploy

permissions: write-all

on:
  workflow_call:

jobs:
  upload-lambda:
    name: Upload Lambda to S3
    runs-on: ubuntu-latest
    continue-on-error: true

    env:
      AWS_REGION: us-east-1

    strategy:
      matrix:
        include:
          - environment: production
            AWS_ACCOUNT_ID: '629216831935'

          - environment: development
            AWS_ACCOUNT_ID: '954701063678'

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }} # required for git push
          fetch-depth: 0 # required for Nx affected

      - uses: ./.github/actions/prepare-to-run-nx

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: arn:aws:iam::${{ matrix.AWS_ACCOUNT_ID }}:role/GitHubActions-Elrond
          aws-region: ${{ env.AWS_REGION }}

      - run: pnpm upload-lambdas-and-metadata ${{ matrix.environment }}

      - name: Report failed deployment
        uses: ./.github/actions/send-slack-message
        if: ${{ failure() }}
        with:
          slack_webhook_url: ${{ vars.SLACK_WEBHOOK_URL_DEPLOY_FAILED }}
          message: Deploy Failed
